version: '3.9'

services:
  # mongodb:
  #   image: mongo:5.0.6
  #   container_name: mongodb-mkp
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123456
  #     MONGO_INITDB_DATABASE: mkp
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - mongo-network

  redis:
    image: redis:6.2.5
    restart: unless-stopped
    command: --port 6380
    ports:
      - 6380:6380

  # redis-commander:
  #   depends_on:
  #     - redis
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: ghcr.io/joeferner/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8081:8081"
